### PR TITLE
Add all possible routes to router_p2v test

### PR DESCRIPTION
**Pull request by Mopster**
Test now contains all the possible routes between the different VM's to give a more detailed test result of the environment

### CODE REVIEW

**Comment by akry** [comment]
We should first fix race conditions happened in the p2v test then add more test cases.

**Comment by Metallion** [comment]
Having more test results to work with could ease the process of hunting for those race conditions though. But the question is how much more time the tests take with these changes.

**Comment by Metallion** [comment]
At this moment I think these added tests don't give us enough added coverage to justify for the time they take to execute. It would be better if we could add them as an option than can be enabled specifically when needed.

**Comment by rakshasa** [comment]
```
pull request -- Took 15 min on vnetmaki01.phys024a.opty
develop -- Took 13 min on vnetmaki01.phys024a.opty
```

+1 ?

**Comment by rakshasa** [comment]
Also those tests should be possible to run in parallel.

**Comment by Metallion** [comment]
Only a 2 minute difference huh. Ok then let's merge this. :)

Technically it's possible to run these tests in parallel but we'd have to set up a few more copies of the integration test environment. We can discuss how to go about that bit at the office some time soon.

**Pull request merged**
