### PR TITLE
Feature topology rl

### PR DESCRIPTION
**Pull request by rakshasa**
Topology with simple over/underlay that uses the first host interface it finds for each datapath.

### CODE REVIEW

**Comment by Metallion** [comment]
Could you add an integration test for this before we merge?

**Comment by Metallion** [comment]
Rerunning the CI on here since a bug was fixed on develop where the integration test could return faulty results.

**Comment by Metallion** [comment]
It looks like the integration test doesn't automatically merge in master and ran the broken version. There was actually a failure but it reported success.

```
18:08:12 Failures:
18:08:12 
18:08:12   1) event datapath add behaves like vm(reachable) vm1() mac2mac reachable to vm4(vnet2)
18:08:12      Failure/Error: expect(vm).to be_reachable_to(vm4)
```

I have changed it so the integration test merges in develop before running and will now rerun it.

**Comment by Metallion** [comment]
It looks like the way I had the CI setup ran the integration test on another environment where the rpms weren't built. I've changed the configuration so this can't happen any more but unfortunately it means rpms have to be built every time the integration test is run. Rerunning from the rpmbuild step.

**Comment by Metallion** [comment]
Now the integration test returned the correct result.

**Comment by akry** [comment]
It seems an reasonable implementation that creates dp_nw and dp_rl automatically. 

1) Is topology_datapath necessary? There's no implementation of `topology_added_datapath`

2) Do you have any desire to create route and route_link automatically like as this PR? I think the ideal case is that the users pass topology_manager only network and simulated interface(which behaves the gw of the vnet), then topology_manager creates route, route_link, dp_nw and dp_rl.

**Comment by rakshasa** [comment]
The topology_datapath is for the proper topology mode, while 'simple_over/underlay' is a dumb mode you use when you only have one host interface.

**Comment by rakshasa** [comment]
Also route/route_link is outside of the scope of this PR and hasn't been considered yet.

**Comment by akry** [comment]
Do you mean implementaion of `topology_added_datapath` is not completed yet?

**Comment by rakshasa** [comment]
There's several things that still needs work, however that won't be done until I start working on a more complex topology mode.

**Comment by akry** [comment]
there would be no problem if topology datapath is on a half way since nothing happens even if an entry is created. so +1

**Pull request merged**
