### PR TITLE
Bundle update

### PR DESCRIPTION
**Pull request by Metallion**
I ran `bundle update` on both the vnet and vnctl directories. I think we should do this about once a month or so.

### CODE REVIEW

**Comment by Metallion** [comment]
So we have ourselves some failing unit tests. From what I've seen it looks like the problem is related to the order rspec's let blocks are loaded in.

**Comment by Metallion** [comment]
Fixed one issue in the unit tests. The way the MacLease fabricator was used was off. Now it makes me wonder why it was working before the bundle update and I will investigate that before merging.

Anyway, first things first. Some other (all database related) unit tests are still red.

**Comment by akry** [comment]
We might want to create a CI job for monthly `bundle update`.

**Comment by Metallion** [comment]
Closed in favour of https://github.com/axsh/openvnet/pull/345

**Pull request closed without merging**
