### PR TITLE
Added warning message for datapath_mac_group to vnmgr

### PR DESCRIPTION
**Pull request by Metallion**

### CODE REVIEW

**Comment by rakshasa** [comment]
The code is not clear enough IMO, a few bad practices like assigning in the if statement without a clear syntax.

Assign mg_uuid (or dp_mg_uuid?) before the if check, then check if nil then error. Then 'else if' not found in db results in error. The branching flow feels more natural in that case. Current code does not do the checks in the cleanest order.

**Comment by rakshasa** [comment]
+1

**Comment by rakshasa** [comment]
+1

**Comment by Metallion** [comment]
The problem with the previous rspec failure was a race condition in filter2manager.

```
14:51:53 Failures:
14:51:53 
14:51:53   1) Vnet::Core::Filter2Manager#added_static when protocol is arp and passthrough is disabled adds the static
14:51:53      Failure/Error: expect(flows).to include flow(ingress)
14:51:53 
14:51:53        expected [#<Vnet::Openflow::Flow:0x007fe0cb4e3348 @params={:table_id => 46, :priority => 90, :match => {:eth_type => 2054}, :actions => nil, :options => {:cookie => 1008806389545435136, :goto_table => 90}}>, #<Vnet::Openflow::Flow:0x007fe0cd884770 @params={:table_id => 46, :priority => 10, :match => {:metadata => 504403158265495553, :metadata_mask => 18374686481819107327}, :actions => nil, :options => {:cookie => 1297036692682702849}}>, #<Vnet::Openflow::Flow:0x007fe0cd88fc88 @params={:table_id => 16, :priority => 10, :match => {:metadata => 504403158265495553, :metadata_mask => 18374686481819107327}, :actions => nil, :options => {:cookie => 1297036692682702849}}>] to include #<Vnet::Openflow::Flow:0x007fe0d42ae560 @params={:table_id => 46, :priority => 24, :match => {:eth_type => 2048, :ipv4_src => 2, :ipv4_src_mask => #<IPAddr: IPv4:192.0.0.0/255.255.255.255>, :ip_proto => 1, :metadata => 504403158265495553, :metadata_mask => 18374686481819107327}, :actions => nil, :options => {:cookie => 1297036692682702849}}>
14:51:53        Diff:
14:51:53        @@ -1,2 +1,4 @@
14:51:53        -[#<Vnet::Openflow::Flow:0x007fe0d42ae560 @params={:table_id=>46, :priority=>24, :match=>{:eth_type=>2048, :ipv4_src=>2, :ipv4_src_mask=>#<IPAddr: IPv4:192.0.0.0/255.255.255.255>, :ip_proto=>1, :metadata=>504403158265495553, :metadata_mask=>18374686481819107327}, :actions=>nil, :options=>{:cookie=>1297036692682702849}}>]
14:51:53        +[#<Vnet::Openflow::Flow:0x007fe0cb4e3348 @params={:table_id=>46, :priority=>90, :match=>{:eth_type=>2054}, :actions=>nil, :options=>{:cookie=>1008806389545435136, :goto_table=>90}}>,
14:51:53        + #<Vnet::Openflow::Flow:0x007fe0cd884770 @params={:table_id=>46, :priority=>10, :match=>{:metadata=>504403158265495553, :metadata_mask=>18374686481819107327}, :actions=>nil, :options=>{:cookie=>1297036692682702849}}>,
14:51:53        + #<Vnet::Openflow::Flow:0x007fe0cd88fc88 @params={:table_id=>16, :priority=>10, :match=>{:metadata=>504403158265495553, :metadata_mask=>18374686481819107327}, :actions=>nil, :options=>{:cookie=>1297036692682702849}}>]
14:51:53      Shared Example Group: "added_static" called from ./spec/vnet/core/filters2_spec.rb:113
14:51:53      # ./vendor/bundle/ruby/2.1.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:87:in `block in <module:Support>'
14:51:53      # ./vendor/bundle/ruby/2.1.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:96:in `call'
14:51:53      # ./vendor/bundle/ruby/2.1.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:96:in `notify_failure'
14:51:53      # ./vendor/bundle/ruby/2.1.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/fail_with.rb:27:in `fail_with'
14:51:53      # ./vendor/bundle/ruby/2.1.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
```

This is unrelated to this pull request and will be dealt with in another one.

**Comment by Metallion** [comment]
DNS service failed in the integration test. I wonder what's up with that. >.>

```
17:13:40 rspec ./spec/service_spec.rb:124 # service dns after adding dns record 'vm3' vm1 should resolve google.com 
17:13:40 rspec ./spec/service_spec.rb:128 # service dns after adding dns record 'vm3' vm1 should resolve vm3
```

**Pull request merged**
