### PR TITLE
Rpm version tags

### PR DESCRIPTION
**Pull request by Mopster**
Added version name to the RPM's filename. 

The tag's name is being retrieved by 'git describe'. For the master branch, we will always have a tagged commit, so this will return the tag's name like 'v0.6'. 
```
openvnet-v0.6.fpm0-1.noarch.rpm
openvnet-vna-v0.6.fpm0-1.noarch.rpm
openvnet-webapi-v0.6.fpm0-1.noarch.rpm
openvnet-vnmgr-v0.6.fpm0-1.noarch.rpm
```
For other branches where there are commits after a tag, a hash will appear behind the version number.
```
openvnet-vnctl-v0.6_49_g48d2f8dspot.fpm0-1.noarch.rpm
openvnet-v0.6_49_g48d2f8d.fpm0-1.noarch.rpm
openvnet-vna-v0.6_49_g48d2f8d.fpm0-1.noarch.rpm
openvnet-webapi-v0.6_49_g48d2f8d.fpm0-1.noarch.rpm
openvnet-vnmgr-v0.6_49_g48d2f8d.fpm0-1.noarch.rpm
```

Currently trying to see if we can get this working with Jenkins correctly

### CODE REVIEW

**Comment by Mopster** [comment]
When deploying, the existing  vnet.release-package6 should no longer change the 'current' symlink after running a build on the master branch. This should be left to the manual job 'vnet.stable-release.release-package6'.

**Comment by Mopster** [comment]
Link to issue : https://github.com/axsh/openvnet/issues/314

**Comment by akry** [comment]
How do we specify `RPM_VERSION` ?

**Comment by akry** [comment]
tag?

**Comment by akry** [comment]
I still don't fully understand how the other branches work along with tags.

**Comment by Mopster** [comment]
The job "openvnet.stable-release.release-package6" has a RPM_VERSION field which has to be specified before running the job manually. Only this job will create a new stable release RPM with tagged version.

**Comment by akry** [comment]
RPM packages are created when someone commits to their own branch. Adding one parameter to stable-release job is not enough I guess.

**Comment by akry** [comment]
It seems like there wouldn't be any version name on those packages of feature branch.

http://ci.wakame.jp/job/openvnet.rpmbuild6/2725/console

**Comment by Mopster** [comment]
The current flow has not been changed except for 1 piece.

When the master branch has a new commit, it will still create an RPM, but it won't move the 'current' symlink to the new release folder. That responsibility has been moved to the new p.vnet.stable-release.release-package6' job. So the 'current' symlink will only be put on stable releases.

There is currently no way to get the version on the packages. Jenkins generates its own git tags which interfere with my initial script that uses git-describe to retrieve an useful release tag (for both master (stable release) and develop rpm's). That's why we currently have to work with a stable-release job that has to be started manually.

**Comment by akry** [comment]
:+1:

**Pull request merged**
