### PR TITLE
Update rspec

### PR DESCRIPTION
**Pull request by Metallion**
Updated the rspec gem, fixed any issues that gave us and fixed deprecated code.

### CODE REVIEW

**Comment by akry** [comment]
How often do you expect to update the gems? I think every version release might be the best time.

**Comment by Metallion** [comment]
I was thinking more like monthly. Doing it just before release could result in unexpected surprises. It might also be a good idea to do a gem freeze about two months or so before a version release.

**Comment by akry** [comment]
:+1:

**Comment by Metallion** [comment]
The two integration test failures on July 26th both have the same issue.

```
17:59:55 sed: can't read /etc/openvnet/vna.conf: No such file or directory
17:59:55 sed: can't read /etc/openvnet/vna.conf: No such file or directory
17:59:55 Build step 'Execute shell' marked build as failure
```

Unfortunately I can no longer log into the CI environment to investigate since it gets rebuilt regularly. I am going to run the integration test a few more times to make sure this branch hasn't introduced a new problem.

**Pull request merged**
