### PR TITLE
Update gems

### PR DESCRIPTION
**Pull request by Metallion**
* Updated the gems for both OpenVNet itself and the integration test.
* Updated ruby from 2.2.0 to 2.3.0 for the integration test since one of the newer gems required that.
* Removed unused gems from the integration test.
* Removed an unneeded and broken OpenVNet yum repo that was getting installed in the integration test nodes.

### CODE REVIEW

**Comment by Metallion** [comment]
CI Passed on CentOS 6. https://ci.openvnet.org/job/el6/job/update-gems-fix-integ/6/
CentOS 7 result pending.

**Comment by toros11** [comment]
This file needs to be updated as well.

https://github.com/axsh/openvnet/blob/23b53ee395d8838a487f616bb2635ddb31a5ba05/client/vnctl/Gemfile.lock

**Comment by Metallion** [comment]
Updated it. CI's curently running.

Btw, I noticed we still have [a Gemfile for our old fpm based packages](https://github.com/axsh/openvnet/tree/develop/deployment/packagebuild). Looking at the CI, it seems those have been completely replaced by regular rpm spec files. I'm planning to remove it in another PR.

**Comment by Metallion** [comment]
CI result's the same as the above.

https://ci.openvnet.org/job/el6/job/update-gems-fix-integ/7/console
https://ci.openvnet.org/job/el7/job/update-gems-fix-integ/2/console

**Pull request merged**
