### PR TITLE
Added changelog

### PR DESCRIPTION
**Pull request by Metallion**

### CODE REVIEW

**Comment by YamazakiYasuhiro** [comment]
how about a documentation? should be described only feature?

**Comment by Metallion** [comment]
Documentation is not necessary. This is purely a changelog of the code.

**Comment by akry** [comment]
Should we clearly mention that MAC2MAC is our own protocol? Because it's not defined on RFC.

**Comment by Metallion** [comment]
Yeah maybe we should. I'll add it.

**Comment by akry** [comment]
:+1:

**Pull request merged**
