### PR TITLE
Ci garbage collection

### PR DESCRIPTION
**Pull request by toros11**
Implements garbage collection of rpms, docker images and cached images used in the integration test.

### CODE REVIEW

**Comment by Metallion** [comment]
This is still red. https://ci.openvnet.org/job/garbage_collection/28/console Make sure to test it after you make changes. ;)

**Comment by toros11** [comment]
The only reason I can think of it failing is because this shows up
`[2] sudo: no tty present and no askpass program specified`
which looks like a machine setting problem to me.

It actually shows up in the garbage_collection on openvdc as well so I didn't think much of it then since it kept passing but we don't try to delete dangling images there too. The script that fails does not fail on the multibox node.

**Comment by Metallion** [comment]
Looks good to me now. Thanks for the fix. ^_^

**Comment by Metallion** [comment]
Changed the GC job to run from develop now that it's merged. This branch can be deleted now. *click*

**Pull request merged**
