### PR TITLE
Feature mac ranges

### PR DESCRIPTION
**Pull request by rakshasa**
Adds mac range groups allowing the user to automatically allocate mac addresses for dp_nw/rl by setting 'datapath_mac_group' in common.conf, and to pass a mac range group when creating interfaces.

### CODE REVIEW

**Comment by akry** [comment]
How do we use `datapath_mac_group` in common.conf?

**Comment by rakshasa** [comment]
```
registry {
  adapter "redis"
  host "192.168.61.101"
  port 6379
}

db {
  adapter "mysql2"
  host "192.168.61.101"
  database "vnet"
  port 3306
  user "root"
  password ""
}

datapath_mac_group "mrg-dpg"
```

```
echo; curl -s -X POST \
--data-urlencode uuid=mrg-dpg \
http://localhost:9090/api/mac_range_groups

echo; curl -s -X POST \
--data-urlencode begin_mac_address=08:00:27:aa:00:00 \
--data-urlencode end_mac_address=08:00:27:aa:ff:ff \
http://localhost:9090/api/mac_range_groups/mrg-dpg/mac_ranges
```

The common.conf entry needs to be on every node that calls node_api, e.g. if using 'direct' db access then webapi node also needs the entry.

**Comment by akry** [comment]
I think this configuration is not user-friendly. It requires `mrg-mng` is created beforehand of launching vnmgr, webapi and vna, but mac_range can be created after the daemons got launched.

According to [IEEE](http://standards-oui.ieee.org/oui.txt) there are several private mac address ranges. Why don't we internally use some private mac address ranges by default?

**Comment by Metallion** [comment]
Using a private range by default sounds like a good idea but it should be documented. The `datapath_mac_group` option could be commented out by default. When it's commented out, the default range will be used and when it's set, the mac range in it will be used. There should be a comment above it explaining its behaviour.

**Comment by rakshasa** [comment]
The 'datapath_mac_group' uuid is only looked up when dp_nw/rl are created, it does not have to exist when vnmgr or webapi launches.

Also we cannot use any specific private ranges since we do not know if they are already in use by the user. Thus in my opinion the user should be forced to select the range when setting up openvnet.

**Comment by rakshasa** [comment]
Also we always need to have a mac range group from which to get mac addresses, so if the user doesn't want to see the creation of it then it should be automatically created by scripts that set up the db in a user-friendly way.

Making guesses at what addresses are ok should not belong in core.

**Comment by rakshasa** [comment]
There are going to be plenty of other settings that will be needed when e.g. topology is implemented, and we can't create hardcoded defaults for those.

Thus we're probably going to have to go with something like install, db creation, launch vnmgr/webapi, call pre-made script to setup initial environment of type 'foo'.

**Comment by Metallion** [comment]
Good point about not knowing what the user is using already. It could be in the installation guide or with a script as you say then.

I imagine that when it's not set, OpenVNet should still work the same way it currently does, right? At no point should it crash or not work because the option is not set. Only automatic setup of dp_nw/rl should depend on it.

**Comment by rakshasa** [comment]
Yes, only automatic setup fails.

**Comment by akry** [comment]
Setting hard-coded default mac range is not that bad idea I think as long as there's a way to change the default value (e.g. config file, install script...). Why not to embed default value in it and mention about it on the document. If the default value is not opted to users, they can freely change it. Just rely on install script is not good idea because currently there is no install script for openvnet

**Comment by akry** [comment]
I am worried about adding one more step for openvnet installation (setting up proper mac range). The point of automatic generation for dp_nw/rl is lessen the hurdle for installing openvnet, but this PR is just adding another step for installation.

**Comment by Metallion** [comment]
I'm a little worried about database relations when using a hard coded value though. Currently in the config file we're using the UUID of a mac range. If we hard code a default range, it would not be in the database. That means the code will need to handle both mac ranges in the database and the hard coded one. It sounds like it will make the code more complex.

There is indeed currently no install script. For now, an extra step in the installation guide will do I think. (It should be added in this pull request)

An installation script similar to the one in Wakame's installation guide can be added in a new branch but I don't think it's a priority right now.

I understand your concern about adding installation steps but I still think it is different from dp_nw. The mac range is just a single step in the installation guide and the default one will work for 99% of all environments while dp_nw is very specific to each environment.

The thing is Wakame-vdc also has mac range setup in its installation guide and all feedback we've gotten so far on that guide is that it's easy to install.

**Comment by akry** [comment]
It does not mean that the hard coded mac range would not be in the database. Once vnmgr finds that there's no UUID of mac range specified, it internally creates a new mac range which should be the default mac range for dp_nw/rl.

Moreover,

https://github.com/axsh/openvnet/blob/feature-mac-ranges/vnet/lib/vnet/node_api/datapath_generic.rb#L18-L27

this should be chained from the web api of either/both network or datapath, not from datapath_network. But it beyonds the realm of this PR so the above should be done in another branch.

**Comment by akry** [comment]
:+1:

**Comment by Metallion** [comment]
Could you add an issue for those lines of code you posted? We can continue that discussion there.

I'll be merging this since you gave the +1.

**Comment by Metallion** [comment]
Another thing I thought about. If the configuration mac range is not set and the user tries to use automatic dp/rl creation, how will OpenVNet behave? An error should be returned as early in the process as possible. Perhaps a check in the WebAPI?

**Comment by akry** [comment]
If the default mac range is not specified in the configuration file, users simply cannot use automatic creation. They have to specify mac addresses for dp_nw/rl manually.

**Comment by Metallion** [comment]
I understand that. What I'm saying is that OpenVNet should return an error as early as possible, clearly informing the user that they can't use automatic creation because the default mac range is not set. It should not start processing the request and then crash.

**Comment by akry** [comment]
It's not necessary to return an error as long as datapath_mac_address is passed over web api. In turn it might be better to show warning messages to uses that like "datapath_mac_address is obsoleted. set the default mac range and use automatic creation is recommended"

**Comment by rakshasa** [comment]
When you want to use automatic dp_nw/rl creation you need to create a topology item that handles it for the networks and route links you create.

So when the topology is created it can complain when it doesn't get assigned a mac_range_group nor is the default set.

This does however just kick things down the road as the user needs to know they're making networks or route links without topologies.

**Comment by Metallion** [comment]
Do you have the whole system in a design document anywhere? I feel like I don't have an idea of the bigger picture you have in mind. I remember you had one for n-hop but not sure about automatic dp_nw/rl.

**Comment by rakshasa** [comment]
I wrote the n-hop design document as the feature itself was so complex and needed to be worked out on paper.

For topology the overall design is simple enough that it isn't written down anywhere.

A network is assigned to a topology, the topology knows what physical networks it should use and from that it knows what host interface to use for the dp_nw. Add some magic and you no longer need to make every dp_*.

**Comment by Metallion** [comment]
Still waiting for mac range setup to be added to the installation guide before merging. you can add it by editing the files under [openvnet/docs](https://github.com/axsh/openvnet/tree/feature-mac-ranges/docs)

**Comment by rakshasa** [comment]
Updated docs, and added to common.conf a default mrg-dpg, which does not have any impact on older setups using explicit mac addresses.

**Pull request merged**
