### PR TITLE
Feature active_route_link_manager

### PR DESCRIPTION
**Pull request by rakshasa**
Added a manager for tracking active route links on datapaths. Same functionality as active_network_manager, and is needed to auto-create dp_rl's with topology manager.

### CODE REVIEW

**Comment by akry** [comment]
:+1:

**Comment by Metallion** [comment]
Gonna run the CI on this one more time before merging to make sure it still works after merging filter2manager. https://github.com/axsh/openvnet/pull/425

**Comment by Metallion** [comment]
```
14:12:41 --------------------------------------------------
14:12:41 simple: success
14:12:41 router_v2v: failure
14:12:41 router_p2v: success
14:12:41 event: failure
14:12:41 service: success
14:12:41 secg: failure
14:12:41 secg_reference: success
14:12:41 edge: success
14:12:41 --------------------------------------------------
```

3 Failures. Let's check if the CI on develop is still green.

**Comment by Metallion** [comment]
Confirmed that develop is green. The problem needs to be fixed in this branch before merging.

**Comment by Metallion** [comment]
Looks like this rspec failure was a problem when trying to install Trema. Going to run the CI again.

**Comment by rakshasa** [comment]
This branch seems to pass the CI tests without issues now.

**Pull request merged**
