### PR TITLE
fix missing operator.

### PR DESCRIPTION
**Pull request by unakatsuo**
simlilar to #309 (7bf2d6dadb6).

### CODE REVIEW

**Comment by Metallion** [comment]
Both integration test failures have the same result.

```
16:40:30 --------------------------------------------------
16:40:30 simple: success
16:40:30 router_v2v: success
16:40:30 router_p2v: success
16:40:30 event: failure
16:40:30 service: success
16:40:30 secg: success
16:40:30 secg_reference: success
16:40:30 edge: failure
16:40:30 --------------------------------------------------
```

Interesting... So event and edge break if it is possible for the above method to return `false`.  :astonished:

**Comment by unakatsuo** [comment]
```
E, [2015-07-01T05:16:04.589817 #6354] ERROR -- : 0x0000aaaaaaaaaaaa tunnel_manager: host datapath network 1 already added
D, [2015-07-01T05:16:04.648079 #6354] DEBUG -- : 0x0000aaaaaaaaaaaa datapath/host: activating network 1 on dp-new/4
E, [2015-07-01T05:16:04.648801 #6354] ERROR -- : 0x0000aaaaaaaaaaaa tunnel_manager: host datapath network 1 already added
D, [2015-07-01T05:16:04.667770 #6354] DEBUG -- : 0x0000aaaaaaaaaaaa datapath/host: adding datapath network 3 to dp-new/4
D, [2015-07-01T05:16:04.667890 #6354] DEBUG -- : 0x0000aaaaaaaaaaaa datapath/host: activating network 3 on dp-new/4
E, [2015-07-01T05:16:04.668591 #6354] ERROR -- : 0x0000aaaaaaaaaaaa tunnel_manager: host datapath network 3 already added
D, [2015-07-01T05:16:04.716038 #6354] DEBUG -- : 0x0000aaaaaaaaaaaa datapath/host: adding datapath network 4 to dp-new/4
D, [2015-07-01T05:16:04.716148 #6354] DEBUG -- : 0x0000aaaaaaaaaaaa datapath/host: activating network 4 on dp-new/4
E, [2015-07-01T05:16:04.716868 #6354] ERROR -- : 0x0000aaaaaaaaaaaa tunnel_manager: host datapath network 4 already added
```

**Comment by Metallion** [comment]
This is old but let's see what the CI has to say about it.

**Comment by Metallion** [comment]
Since this breaks the CI and hasn't been fixed for nearly a year, I'm closing it.

**Pull request closed without merging**
